version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: chatboot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: gerenciador_educacional
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: chatboot-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  mysql_data:
  ollama_data: 